// <auto-generated />
using IKM6.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IKM6.Migrations
{
    [DbContext(typeof(IKM6Context))]
    partial class IKM6ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IKM6.Models.item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("item");
                });

            modelBuilder.Entity("IKM6.Models.property", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("property");
                });

            modelBuilder.Entity("IKM6.Models.values", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("property_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("property_id");

                    b.ToTable("values");
                });

            modelBuilder.Entity("itemvalues", b =>
                {
                    b.Property<int>("Itemsid")
                        .HasColumnType("integer");

                    b.Property<int>("Valuesid")
                        .HasColumnType("integer");

                    b.HasKey("Itemsid", "Valuesid");

                    b.HasIndex("Valuesid");

                    b.ToTable("itemvalues");
                });

            modelBuilder.Entity("IKM6.Models.values", b =>
                {
                    b.HasOne("IKM6.Models.property", "property")
                        .WithMany("values")
                        .HasForeignKey("property_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("property");
                });

            modelBuilder.Entity("itemvalues", b =>
                {
                    b.HasOne("IKM6.Models.item", null)
                        .WithMany()
                        .HasForeignKey("Itemsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IKM6.Models.values", null)
                        .WithMany()
                        .HasForeignKey("Valuesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IKM6.Models.property", b =>
                {
                    b.Navigation("values");
                });
#pragma warning restore 612, 618
        }
    }
}
